CREATE TABLE USERS;


CREATE TABLE USER (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(USER_ID)
);

CREATE TABLE MESSAGE (
    MESSAGE_ID INT NOT NULL AUTO_INCREMENT,
    SENDER_ID INT NOT NULL,
    RECEIVER_ID INT, -- NULL for global messages
    CONTENT TEXT NOT NULL, -- Encrypted message content
    IS_FILE BOOLEAN DEFAULT FALSE,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(MESSAGE_ID),
    FOREIGN KEY (SENDER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (RECEIVER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE FILE_META (
    FILE_ID INT NOT NULL AUTO_INCREMENT,
    MESSAGE_ID INT NOT NULL,
    FILENAME VARCHAR(255) NOT NULL,
    FILETYPE VARCHAR(100) NOT NULL,
    CLOUD_REFERENCE VARCHAR(255) NOT NULL, -- Reference to cloud storage
    PRIMARY KEY(FILE_ID),
    FOREIGN KEY (MESSAGE_ID) REFERENCES MESSAGE(MESSAGE_ID)
);